### EXPERIMENT PARAMS ###
experiment_version: 'fcn32'
experiment_desc: 'Our dataset'
checkpoint_save_path: 'experiments/fcn8/weights/fcn8_{epoch:02d}-{val_loss:.2f}.h5'
log_save_path: 'experiments/fcn8/logs'
hist_save_path: 'experiments/fcn8/model_hist.json'
save_base: 'experiments/fcn8/'

### MODEL PARAMS ###
conv_dropout_prob: 0.1
batch_norm_momentum: 0.9
fc_dropout_prob: 0.2

### CALLBACK PARAMS ###
early_stop_monitor: 'val_loss'
patience: 5
weights_only: True
checkpoint_monitor: 'val_loss'
checkpoint_mode: 'min'
save_best: True
tensorboard_update_freq: 'batch'

### FIT PARAMS ###
epochs: 30000
batch_size: 128
verbose: 1