### EXPERIMENT PARAMS ###
experiment_version: 'unet'
experiment_desc: 'Our dataset'
checkpoint_save_path: 'experiments/unet/weights/unet_{epoch:02d}-{val_loss:.2f}.h5'
log_save_path: 'experiments/unet/logs'
hist_save_path: 'experiments/unet/model_hist.json'
save_base: 'experiments/unet/'

### MODEL PARAMS ###
conv_dropout_prob: 0.1
batch_norm_momentum: 0.9
fc_dropout_prob: 0.2

### CALLBACK PARAMS ###
early_stop_monitor: 'val_loss'
patience: 5
weights_only: True
checkpoint_monitor: 'val_loss'
checkpoint_mode: 'min'
save_best: True
tensorboard_update_freq: 'batch'

### LEARNING RATE PARAMS ###
initial_learning_rate: 0.016
decay_steps: 8000
decay_rate: 0.64
staircase: True

### FIT PARAMS ###
epochs: 30000
batch_size: 128
shuffle_seed: 29310
verbose: 1